name: core_network
description: Networking (Dio, Retrofit, JSON)
version: 0.1.0
publish_to: "none"
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
dev_dependencies:
  build_runner: ^2.4.10
  json_serializable: ^6.9.0
  retrofit_generator: ^8.1.0
  test: any
